spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true
#    show-sql: true System.out.println()

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace